# version: "3.9"
services:
  demo_api:
    build: ./demo_app
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - APP_WORKERS=2
      - APP_THREADS=4
      - APP_MIN_DELAY_MS=50
      - APP_MAX_DELAY_MS=300
      - APP_SPIKE_ERROR_RATE=0.02
